# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 03:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('so', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='expire_seconds',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='website',
            name='sleep_seconds',
            field=models.IntegerField(default=3),
        ),
    ]
