# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 07:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('so', '0002_auto_20170320_0341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='title',
            field=models.CharField(max_length=64, verbose_name='aaa'),
        ),
    ]
