# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 07:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('so', '0003_auto_20170320_0750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='expire_seconds',
            field=models.IntegerField(default=0, verbose_name='页面过期时间'),
        ),
        migrations.AlterField(
            model_name='website',
            name='schedule_type',
            field=models.SmallIntegerField(choices=[(0, '每小时'), (1, '每天'), (2, '每周'), (3, '每月')], default=1, verbose_name='爬取周期'),
        ),
        migrations.AlterField(
            model_name='website',
            name='sleep_seconds',
            field=models.IntegerField(default=3, verbose_name='爬取间隔时间'),
        ),
        migrations.AlterField(
            model_name='website',
            name='title',
            field=models.CharField(max_length=64, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='websitealloweddomain',
            name='domain',
            field=models.CharField(max_length=256, verbose_name='主机名'),
        ),
        migrations.AlterField(
            model_name='websiteselector',
            name='key_name',
            field=models.CharField(max_length=24, verbose_name='名称'),
        ),
    ]
