# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 08:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('so', '0004_auto_20170320_0754'),
    ]

    operations = [
        migrations.AddField(
            model_name='websiteselector',
            name='website',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='so.Website'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='websiteurlpattern',
            name='website',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='so.Website'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='website',
            unique_together=set([('user', 'title')]),
        ),
        migrations.AlterUniqueTogether(
            name='websitealloweddomain',
            unique_together=set([('website', 'domain')]),
        ),
        migrations.AlterUniqueTogether(
            name='websiteselector',
            unique_together=set([('website', 'key_name')]),
        ),
        migrations.AlterUniqueTogether(
            name='websiteurlpattern',
            unique_together=set([('website', 'pattern_type', 'pattern')]),
        ),
    ]
