# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-18 19:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('so', '0006_auto_20170408_0835'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='website',
            options={'ordering': ['-id']},
        ),
    ]
