# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-24 14:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('so', '0007_auto_20170418_1947'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpiderTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('logs', models.TextField(blank=True, default='', null=True)),
                ('status', models.SmallIntegerField(choices=[(0, 'unfinished'), (1, 'finish')], default=0)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='so.Website')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
