# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-29 04:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('so', '0008_spidertask'),
    ]

    operations = [
        migrations.AddField(
            model_name='spidertask',
            name='spider',
            field=models.CharField(default='', max_length=128),
        ),
    ]
