# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-29 07:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('so', '0009_spidertask_spider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spidertask',
            name='spider',
            field=models.CharField(db_index=True, default='', max_length=128),
        ),
    ]
